services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=danslebon
      - MONGO_INITDB_ROOT_PASSWORD=tuconnaiiiiss
    volumes:
      - mongodb_data:/data/db
    networks:
      - e-commerce-network

  product-service:
    build:
      context: ./services/product-service
    container_name: product-service
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://danslebon:tuconnaiiiiss@mongodb:27017/ecommercevue?authSource=admin
    depends_on:
      - mongodb
    networks:
      - e-commerce-network

  auth-service:
    build:
      context: ./services/auth-service
    container_name: auth-service
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://danslebon:tuconnaiiiiss@mongodb:27017/ecommercevue?authSource=admin
      - JWT_SECRET=efrei_super_pass
    depends_on:
      - mongodb
    networks:
      - e-commerce-network

  order-service:
    build:
      context: ./services/order-service
    container_name: order-service
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://danslebon:tuconnaiiiiss@mongodb:27017/ecommercevue?authSource=admin
      - JWT_SECRET=efrei_super_pass
    depends_on:
      - mongodb
    networks:
      - e-commerce-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    environment:
      - VITE_PRODUCT_SERVICE_URL=http://product-service:3000
      - VITE_AUTH_SERVICE_URL=http://auth-service:3001
      - VITE_ORDER_SERVICE_URL=http://order-service:3002
    depends_on:
      - product-service
      - auth-service
      - order-service
    networks:
      - e-commerce-network

networks:
  e-commerce-network:

volumes:
  mongodb_data:
